version: '3'

services:
    app:
        build:
            context: docker/app
            dockerfile: Dockerfile
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        env_file:
            - ./docker/app/.env
        volumes:
            - '.:/var/www/html/:delegated'

    app_xdebug:
        build:
            context: docker/app
            dockerfile: Dockerfile_xdebug
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        env_file:
            - ./docker/app/.env
        volumes:
            - '.:/var/www/html/:delegated'

    nginx:
        image: nginx
        volumes:
            - '.:/var/www/html/'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/config/ssl.conf:/etc/nginx/config/ssl.conf'
            - './docker/nginx/config/ssl-params.conf:/etc/nginx/config/ssl-params.conf'
            - './docker/nginx/config/gzip.conf:/etc/nginx/config/gzip.conf'
            - './docker/nginx/config/pki/dhparam.pem:/etc/nginx/pki/dhparam.pem'
            - './docker/nginx/config/pki/insecure.crt:/etc/nginx/pki/certs/insecure.crt'
            - './docker/nginx/config/pki/insecure.key:/etc/nginx/pki/private/insecure.key'
        ports:
            - '127.0.0.1:80:80'
            - '127.0.0.1:443:443'

networks:
    default:
        external:
            name: 'pxd-docker'
